---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - rsync

- name: Register variable with latest OctoRPKI release
  uri:                                                               
    url: https://api.github.com/repos/cloudflare/cfrpki/releases/latest
    return_content: true
  register: github_reponse
  tags:
    - install

- name: Register variable with debian package
  set_fact:
    cacheable: yes
    debian_package: "{{ item }}"
  when:
    item.name is regex("octorpki.*deb")
  loop:
    "{{ github_reponse.json.assets }}"
  tags:
    - install

- name: Download OctoRPKI deb package
  get_url:
    url: "{{ debian_package.browser_download_url }}"
    dest: "./{{ debian_package.name }}"
  tags:
    - install

- name: Install OctoRPKI deb package
  apt:
    deb: "./{{ debian_package.name }}"
    state: present
  tags:
    - install

- name: Remove deb package from system
  file:
    name: "./{{ debian_package.name }}"
    state: absent
  tags:
    - install

- name: Download TAL from ARIN site
  get_url: 
    url: https://www.arin.net/resources/manage/rpki/arin-rfc7730.tal
    dest: /usr/share/octorpki/tals/arin.tal
  tags:
    - install

- name: Enable OctoRPKI service
  service:
    name: octorpki
    enabled: yes
  notify:
    - restart OctoRPKI
  tags:
    - install

- name: Prepare OctoRPKI config
  template:
    src: default/octorpki.j2
    dest: /etc/default/octorpki
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart OctoRPKI
  tags:
    - configure
